    <header>
        <h1>Explore Tech Events</h1>
        <nav aria-label="Main navigation">
            <ul>
                <li><a href="index.php">Home</a></li>
                <li><a href="insert_details.php">Insert</a></li>
                <li><a href="list_for_changes.php">Modify</a></li>
                <li><a href="contactus.php">Contact Us</a></li>
            </ul>
        </nav>
    </header>
